// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using smart_locking_be.Infrastructure.Persistence;

#nullable disable

namespace smart_locking_be.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924120031_LinkDeliveryRequestNotifications")]
    partial class LinkDeliveryRequestNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("smart_locking_be.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_AuditLog_OccurredAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLog_EntityType_EntityId");

                    b.HasIndex("ActorUserId", "Action", "OccurredAt")
                        .HasDatabaseName("IX_AuditLog_Actor_Action_OccurredAt");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.CompartmentReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeliveryRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LockerCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId")
                        .HasDatabaseName("IX_CompartmentReservation_DeliveryRequestId");

                    b.HasIndex("LockerCompartmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_CompartmentReservation_Active")
                        .HasFilter("\"ReleasedAt\" IS NULL");

                    b.HasIndex("ReturnRequestId")
                        .HasDatabaseName("IX_CompartmentReservation_ReturnRequestId");

                    b.ToTable("CompartmentReservation", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompartmentReservation_ExactlyOneOwner", "(\"DeliveryRequestId\" IS NOT NULL AND \"ReturnRequestId\" IS NULL) OR (\"DeliveryRequestId\" IS NULL AND \"ReturnRequestId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CompartmentReservation_ExpiresAfterReserved", "\"ExpiresAt\" > \"ReservedAt\"");

                            t.HasCheckConstraint("CK_CompartmentReservation_ReleasedAfterReserved", "\"ReleasedAt\" IS NULL OR \"ReleasedAt\" >= \"ReservedAt\"");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.DeliveryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AllocatedCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovalExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalModeSnapshot")
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("CompartmentReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DepositedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasColumnType("character varying");

                    b.Property<string>("FailureDetail")
                        .HasColumnType("text");

                    b.Property<string>("GuestSessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OcrExtractedPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<string>("OcrStatus")
                        .HasColumnType("character varying");

                    b.Property<string>("ParcelImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying");

                    b.Property<string>("RecipientPhoneSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("ReservationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResidentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SessionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipperName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<string>("ShipperPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<Guid>("SystemPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_DeliveryRequest_GuestSessionTokenHash");

                    b.HasIndex("LockerId", "Status")
                        .HasDatabaseName("IX_DeliveryRequest_Locker_Status");

                    b.HasIndex("ResidentProfileId", "Status")
                        .HasDatabaseName("IX_DeliveryRequest_Resident_Status");

                    b.HasIndex("SessionExpiresAt", "Status")
                        .HasDatabaseName("IX_DeliveryRequest_SessionExpiresAt_Status");

                    b.ToTable("DeliveryRequest", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryRequest_AllocatedStatusRequiresCompartment", "\"Status\" NOT IN ('Allocated', 'Deposited') OR \"AllocatedCompartmentId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.DeviceInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpoPushToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpoPushToken")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceInstallation_ExpoPushToken");

                    b.HasIndex("InstallationId")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceInstallation_InstallationId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_DeviceInstallation_UserId_IsActive");

                    b.ToTable("DeviceInstallation", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.EmergencyUnlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LockerCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("IX_EmergencyUnlock_IncidentId");

                    b.HasIndex("LockerId", "RequestedAt")
                        .HasDatabaseName("IX_EmergencyUnlock_Locker_RequestedAt");

                    b.HasIndex("OperatorUserId", "RequestedAt")
                        .HasDatabaseName("IX_EmergencyUnlock_Operator_RequestedAt");

                    b.ToTable("EmergencyUnlock", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedOperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeliveryRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockerCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReporterName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<string>("ReporterPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Incident_CreatedAt");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_Incident_ParcelId");

                    b.HasIndex("LockerId", "Status")
                        .HasDatabaseName("IX_Incident_LockerId_Status");

                    b.HasIndex("Status", "AssignedOperatorUserId")
                        .HasDatabaseName("IX_Incident_Status_AssignedOperator");

                    b.ToTable("Incident", null, t =>
                        {
                            t.HasCheckConstraint("CK_Incident_ResolvedAt", "\"Status\" <> 'Resolved' OR \"ResolvedAt\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.IncidentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .HasColumnType("character varying");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("ActionByUserId", "CreatedAt")
                        .HasDatabaseName("IX_IncidentAction_ActionByUserId_CreatedAt");

                    b.HasIndex("IncidentId", "CreatedAt")
                        .HasDatabaseName("IX_IncidentAction_IncidentId_CreatedAt");

                    b.ToTable("IncidentAction", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("RecoveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Locker_Code");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UX_Locker_DeviceIdentifier");

                    b.HasIndex("OperationalStatus")
                        .HasDatabaseName("IX_Locker_OperationalStatus");

                    b.HasIndex("ConnectionStatus", "LastSeenAt")
                        .HasDatabaseName("IX_Locker_ConnectionStatus_LastSeenAt");

                    b.ToTable("Locker", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerAccessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessMethod")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<Guid?>("DeliveryRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceContext")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying");

                    b.Property<Guid>("LockerCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<Guid?>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId")
                        .HasDatabaseName("IX_LockerAccessEvent_DeliveryRequestId");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_LockerAccessEvent_ParcelId");

                    b.HasIndex("ReturnRequestId")
                        .HasDatabaseName("IX_LockerAccessEvent_ReturnRequestId");

                    b.HasIndex("LockerCompartmentId", "OccurredAt")
                        .HasDatabaseName("IX_LockerAccessEvent_Compartment_OccurredAt");

                    b.HasIndex("LockerId", "OccurredAt")
                        .HasDatabaseName("IX_LockerAccessEvent_Locker_OccurredAt");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_LockerAccessEvent_User_OccurredAt");

                    b.ToTable("LockerAccessEvent", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerCompartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoorStatus")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<int>("HardwareChannel")
                        .HasColumnType("integer");

                    b.Property<string>("HardwareCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoorStatus")
                        .HasDatabaseName("IX_LockerCompartment_DoorStatus");

                    b.HasIndex("OperationalStatus")
                        .HasDatabaseName("IX_LockerCompartment_OperationalStatus");

                    b.HasIndex("LockerId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LockerCompartment_LockerId_Code");

                    b.HasIndex("LockerId", "HardwareChannel")
                        .IsUnique()
                        .HasDatabaseName("UX_LockerCompartment_LockerId_HardwareChannel");

                    b.HasIndex("LockerId", "HardwareCode")
                        .IsUnique()
                        .HasDatabaseName("UX_LockerCompartment_LockerId_HardwareCode");

                    b.ToTable("LockerCompartment", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<Guid?>("LockerCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_LockerEvent_EventType_OccurredAt");

                    b.HasIndex("LockerCompartmentId", "OccurredAt")
                        .HasDatabaseName("IX_LockerEvent_CompartmentId_OccurredAt");

                    b.HasIndex("LockerId", "OccurredAt")
                        .HasDatabaseName("IX_LockerEvent_LockerId_OccurredAt");

                    b.ToTable("LockerEvent", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.MaintenanceActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .HasColumnType("character varying");

                    b.Property<Guid>("MaintenanceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("ActionByUserId", "CreatedAt")
                        .HasDatabaseName("IX_MaintenanceActivity_User_CreatedAt");

                    b.HasIndex("MaintenanceRequestId", "CreatedAt")
                        .HasDatabaseName("IX_MaintenanceActivity_Request_CreatedAt");

                    b.ToTable("MaintenanceActivity", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LockerCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("ResolutionSummary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MaintenanceRequest_CreatedAt");

                    b.HasIndex("LockerId", "Status")
                        .HasDatabaseName("IX_MaintenanceRequest_LockerId_Status");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("IX_MaintenanceRequest_Status_Priority");

                    b.ToTable("MaintenanceRequest", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceRequest_ClosedAt", "\"Status\" <> 'Closed' OR \"ClosedAt\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeliveryRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId")
                        .HasDatabaseName("IX_Notification_DeliveryRequestId");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("IX_Notification_Type_CreatedAt");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("IX_Notification_UserId_IsRead_CreatedAt");

                    b.ToTable("Notification", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notification_ReadState", "\"ReadAt\" IS NULL OR \"IsRead\" = TRUE");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.NotificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeadTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("SystemPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "IsEnabled")
                        .HasDatabaseName("IX_NotificationRule_EventType_IsEnabled");

                    b.HasIndex("SystemPolicyId", "EventType", "Channel")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationRule_Policy_Event_Channel");

                    b.ToTable("NotificationRule", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationRule_LeadTimeMinutes", "\"LeadTimeMinutes\" IS NULL OR \"LeadTimeMinutes\" >= 0");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OperatorAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LockerId")
                        .IsUnique()
                        .HasDatabaseName("UX_OperatorAssignment_ActiveLocker")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.HasIndex("OperatorUserId", "RevokedAt")
                        .HasDatabaseName("IX_OperatorAssignment_Operator_RevokedAt");

                    b.ToTable("OperatorAssignment", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("IX_OtpChallenge_ParcelId");

                    b.HasIndex("DestinationPhone", "Purpose", "CreatedAt")
                        .HasDatabaseName("IX_OtpChallenge_Destination_Purpose_CreatedAt");

                    b.ToTable("OtpChallenge", null, t =>
                        {
                            t.HasCheckConstraint("CK_OtpChallenge_AttemptCount", "\"AttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OverdueCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CalculatedThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ChargeStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatePerHourSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId")
                        .IsUnique()
                        .HasDatabaseName("UX_OverdueCharge_ParcelId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OverdueCharge_Status");

                    b.ToTable("OverdueCharge", null, t =>
                        {
                            t.HasCheckConstraint("CK_OverdueCharge_AmountsAndPeriod", "\"Amount\" >= 0 AND \"RatePerHourSnapshot\" >= 0 AND \"CalculatedThrough\" >= \"ChargeStartAt\"");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("MaxStorageUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParcelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("PickupDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemovalReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_Parcel_DeliveryRequestId");

                    b.HasIndex("ParcelCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Parcel_ParcelCode");

                    b.HasIndex("Status", "MaxStorageUntil")
                        .HasDatabaseName("IX_Parcel_Status_MaxStorageUntil");

                    b.HasIndex("Status", "PickupDueAt")
                        .HasDatabaseName("IX_Parcel_Status_PickupDueAt");

                    b.ToTable("Parcel", null, t =>
                        {
                            t.HasCheckConstraint("CK_Parcel_DeadlineOrder", "\"PickupDueAt\" >= \"StoredAt\" AND \"MaxStorageUntil\" >= \"PickupDueAt\"");

                            t.HasCheckConstraint("CK_Parcel_TerminalTimestamps", "NOT (\"RetrievedAt\" IS NOT NULL AND \"RemovedAt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ParcelStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("character varying");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId", "ChangedAt")
                        .HasDatabaseName("IX_ParcelStatusHistory_ParcelId_ChangedAt");

                    b.HasIndex("ToStatus", "ChangedAt")
                        .HasDatabaseName("IX_ParcelStatusHistory_ToStatus_ChangedAt");

                    b.ToTable("ParcelStatusHistory", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying");

                    b.Property<string>("ExternalOrderCode")
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("OverdueChargeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOrderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentTransaction_ExternalOrderCode")
                        .HasFilter("\"ExternalOrderCode\" IS NOT NULL");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentTransaction_ExternalTransactionId")
                        .HasFilter("\"ExternalTransactionId\" IS NOT NULL");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_PaymentTransaction_RequestedAt");

                    b.HasIndex("OverdueChargeId", "Status")
                        .HasDatabaseName("IX_PaymentTransaction_Charge_Status");

                    b.ToTable("PaymentTransaction", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransaction_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshToken_TokenHash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshToken_UserId_ExpiresAt");

                    b.ToTable("RefreshToken", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshToken_ExpirationAndRevocation", "\"ExpiresAt\" > \"CreatedAt\" AND (\"RevokedAt\" IS NULL OR \"RevokedAt\" >= \"CreatedAt\")");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ResidentBiometric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResidentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TemplateReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResidentProfileId")
                        .IsUnique()
                        .HasDatabaseName("UX_ResidentBiometric_ActiveResident")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.HasIndex("TemplateReference")
                        .HasDatabaseName("IX_ResidentBiometric_TemplateReference");

                    b.ToTable("ResidentBiometric", null, t =>
                        {
                            t.HasCheckConstraint("CK_ResidentBiometric_RevokedAt", "\"RevokedAt\" IS NULL OR \"RevokedAt\" >= \"EnrolledAt\"");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ResidentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DeliveryApprovalMode")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<bool>("FaceRecognitionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("PersonalQrIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonalQrTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryApprovalMode")
                        .HasDatabaseName("IX_ResidentProfile_DeliveryApprovalMode");

                    b.HasIndex("PersonalQrTokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_ResidentProfile_PersonalQrTokenHash");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ResidentProfile_UserId");

                    b.ToTable("ResidentProfile", (string)null);
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ReturnRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AllocatedCompartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompartmentReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("LockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginalParcelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReservationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResidentDepositedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResidentProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("ReturnImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("text");

                    b.Property<string>("ShipperPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("ShipperPickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipperSessionTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReturnCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ReturnRequest_ReturnCode");

                    b.HasIndex("LockerId", "Status")
                        .HasDatabaseName("IX_ReturnRequest_Locker_Status");

                    b.HasIndex("ResidentProfileId", "Status")
                        .HasDatabaseName("IX_ReturnRequest_Resident_Status");

                    b.ToTable("ReturnRequest", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReturnRequest_CompartmentReleasedAt", "\"CompartmentReleasedAt\" IS NULL OR \"AllocatedAt\" IS NULL OR \"CompartmentReleasedAt\" >= \"AllocatedAt\"");

                            t.HasCheckConstraint("CK_ReturnRequest_ReservationExpiresAt", "\"ReservationExpiresAt\" IS NULL OR \"AllocatedAt\" IS NULL OR \"ReservationExpiresAt\" > \"AllocatedAt\"");

                            t.HasCheckConstraint("CK_ReturnRequest_ResidentDepositedAt", "\"ResidentDepositedAt\" IS NULL OR \"AllocatedAt\" IS NULL OR \"ResidentDepositedAt\" >= \"AllocatedAt\"");

                            t.HasCheckConstraint("CK_ReturnRequest_ShipperPickedUpAt", "\"ShipperPickedUpAt\" IS NULL OR \"ResidentDepositedAt\" IS NULL OR \"ShipperPickedUpAt\" >= \"ResidentDepositedAt\"");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.SystemPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClearanceEligibilityAfterHours")
                        .HasColumnType("integer");

                    b.Property<int>("ClearanceNoticeBeforeHours")
                        .HasColumnType("integer");

                    b.Property<int>("CompartmentReservationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying");

                    b.Property<string>("DefaultApprovalMode")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableFaceRecognition")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableOtp")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnablePersonalQr")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableRemoteUnlock")
                        .HasColumnType("boolean");

                    b.Property<int>("GuestSessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ManualApprovalTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStorageHours")
                        .HasColumnType("integer");

                    b.Property<int>("OtpLockoutMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("OtpMaxAttempts")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverdueFeePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OverdueStartAfterHours")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("IX_SystemPolicy_EffectiveFrom");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemPolicy_OneActive")
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemPolicy_Version");

                    b.ToTable("SystemPolicy", null, t =>
                        {
                            t.HasCheckConstraint("CK_SystemPolicy_DurationsAndRates", "\"GuestSessionTimeoutMinutes\" > 0 AND \"ManualApprovalTimeoutMinutes\" > 0 AND \"CompartmentReservationMinutes\" > 0 AND \"OtpMaxAttempts\" > 0 AND \"OtpLockoutMinutes\" > 0 AND \"OverdueStartAfterHours\" >= 0 AND \"OverdueFeePerHour\" >= 0 AND \"MaxStorageHours\" > 0 AND \"ClearanceEligibilityAfterHours\" >= 0 AND \"ClearanceNoticeBeforeHours\" >= 0");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_User_PhoneNumber")
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_User_Role");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_User_Status");

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_LoginIdentifier", "\"PhoneNumber\" IS NOT NULL OR \"Email\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.CompartmentReservation", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.DeliveryRequest", "DeliveryRequest")
                        .WithMany("Reservations")
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "LockerCompartment")
                        .WithMany("Reservations")
                        .HasForeignKey("LockerCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("Reservations")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeliveryRequest");

                    b.Navigation("LockerCompartment");

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.DeliveryRequest", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "AllocatedCompartment")
                        .WithMany("DeliveryRequests")
                        .HasForeignKey("AllocatedCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("DeliveryRequests")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.ResidentProfile", "ResidentProfile")
                        .WithMany("DeliveryRequests")
                        .HasForeignKey("ResidentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.SystemPolicy", "SystemPolicy")
                        .WithMany("DeliveryRequests")
                        .HasForeignKey("SystemPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocatedCompartment");

                    b.Navigation("Locker");

                    b.Navigation("ResidentProfile");

                    b.Navigation("SystemPolicy");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.DeviceInstallation", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "User")
                        .WithMany("DeviceInstallations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.EmergencyUnlock", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.Incident", "Incident")
                        .WithMany("EmergencyUnlocks")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "LockerCompartment")
                        .WithMany("EmergencyUnlocks")
                        .HasForeignKey("LockerCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("EmergencyUnlocks")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.User", "OperatorUser")
                        .WithMany("EmergencyUnlocks")
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Locker");

                    b.Navigation("LockerCompartment");

                    b.Navigation("OperatorUser");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Incident", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "AssignedOperatorUser")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("AssignedOperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.DeliveryRequest", "DeliveryRequest")
                        .WithMany("Incidents")
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "LockerCompartment")
                        .WithMany("Incidents")
                        .HasForeignKey("LockerCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("Incidents")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "Parcel")
                        .WithMany("Incidents")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Incidents")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.User", "ReporterUser")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedOperatorUser");

                    b.Navigation("DeliveryRequest");

                    b.Navigation("Locker");

                    b.Navigation("LockerCompartment");

                    b.Navigation("Parcel");

                    b.Navigation("PaymentTransaction");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.IncidentAction", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "ActionByUser")
                        .WithMany("IncidentActions")
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.Incident", "Incident")
                        .WithMany("Actions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerAccessEvent", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.DeliveryRequest", "DeliveryRequest")
                        .WithMany("AccessEvents")
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "LockerCompartment")
                        .WithMany("AccessEvents")
                        .HasForeignKey("LockerCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("AccessEvents")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "Parcel")
                        .WithMany("AccessEvents")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("AccessEvents")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.User", "User")
                        .WithMany("LockerAccessEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeliveryRequest");

                    b.Navigation("Locker");

                    b.Navigation("LockerCompartment");

                    b.Navigation("Parcel");

                    b.Navigation("ReturnRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerCompartment", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("Compartments")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locker");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerEvent", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "ActorUser")
                        .WithMany("LockerEvents")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "LockerCompartment")
                        .WithMany("Events")
                        .HasForeignKey("LockerCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("Events")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Locker");

                    b.Navigation("LockerCompartment");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.MaintenanceActivity", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "ActionByUser")
                        .WithMany("MaintenanceActivities")
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("Activities")
                        .HasForeignKey("MaintenanceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("MaintenanceRequest");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "CreatedByUser")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.Incident", "Incident")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "LockerCompartment")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("LockerCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Incident");

                    b.Navigation("Locker");

                    b.Navigation("LockerCompartment");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Notification", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.DeliveryRequest", "DeliveryRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Incident", "Incident")
                        .WithMany("Notifications")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "Parcel")
                        .WithMany("Notifications")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany("Notifications")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryRequest");

                    b.Navigation("Incident");

                    b.Navigation("Parcel");

                    b.Navigation("PaymentTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.NotificationRule", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.SystemPolicy", "SystemPolicy")
                        .WithMany("NotificationRules")
                        .HasForeignKey("SystemPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemPolicy");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OperatorAssignment", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "AssignedByUser")
                        .WithMany("CreatedOperatorAssignments")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("OperatorAssignments")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.User", "OperatorUser")
                        .WithMany("OperatorAssignments")
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Locker");

                    b.Navigation("OperatorUser");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OtpChallenge", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "Parcel")
                        .WithMany("OtpChallenges")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.User", "User")
                        .WithMany("OtpChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parcel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OverdueCharge", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "Parcel")
                        .WithOne("OverdueCharge")
                        .HasForeignKey("smart_locking_be.Domain.Entities.OverdueCharge", "ParcelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Parcel", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.DeliveryRequest", "DeliveryRequest")
                        .WithOne("Parcel")
                        .HasForeignKey("smart_locking_be.Domain.Entities.Parcel", "DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.User", "RemovedByUser")
                        .WithMany("RemovedParcels")
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeliveryRequest");

                    b.Navigation("RemovedByUser");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ParcelStatusHistory", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "ChangedByUser")
                        .WithMany("ParcelStatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "Parcel")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.OverdueCharge", "OverdueCharge")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OverdueChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OverdueCharge");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany("ReplacementForTokens")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ResidentBiometric", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.ResidentProfile", "ResidentProfile")
                        .WithMany("Biometrics")
                        .HasForeignKey("ResidentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidentProfile");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ResidentProfile", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "User")
                        .WithOne("ResidentProfile")
                        .HasForeignKey("smart_locking_be.Domain.Entities.ResidentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ReturnRequest", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.LockerCompartment", "AllocatedCompartment")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("AllocatedCompartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.Locker", "Locker")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("smart_locking_be.Domain.Entities.Parcel", "OriginalParcel")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("OriginalParcelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("smart_locking_be.Domain.Entities.ResidentProfile", "ResidentProfile")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("ResidentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocatedCompartment");

                    b.Navigation("Locker");

                    b.Navigation("OriginalParcel");

                    b.Navigation("ResidentProfile");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.SystemPolicy", b =>
                {
                    b.HasOne("smart_locking_be.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedSystemPolicies")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.DeliveryRequest", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("Incidents");

                    b.Navigation("Notifications");

                    b.Navigation("Parcel");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("EmergencyUnlocks");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Locker", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("Compartments");

                    b.Navigation("DeliveryRequests");

                    b.Navigation("EmergencyUnlocks");

                    b.Navigation("Events");

                    b.Navigation("Incidents");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("OperatorAssignments");

                    b.Navigation("ReturnRequests");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.LockerCompartment", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("DeliveryRequests");

                    b.Navigation("EmergencyUnlocks");

                    b.Navigation("Events");

                    b.Navigation("Incidents");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Reservations");

                    b.Navigation("ReturnRequests");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.OverdueCharge", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.Parcel", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("Incidents");

                    b.Navigation("Notifications");

                    b.Navigation("OtpChallenges");

                    b.Navigation("OverdueCharge");

                    b.Navigation("ReturnRequests");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.RefreshToken", b =>
                {
                    b.Navigation("ReplacementForTokens");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ResidentProfile", b =>
                {
                    b.Navigation("Biometrics");

                    b.Navigation("DeliveryRequests");

                    b.Navigation("ReturnRequests");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.ReturnRequest", b =>
                {
                    b.Navigation("AccessEvents");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.SystemPolicy", b =>
                {
                    b.Navigation("DeliveryRequests");

                    b.Navigation("NotificationRules");
                });

            modelBuilder.Entity("smart_locking_be.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedIncidents");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedOperatorAssignments");

                    b.Navigation("CreatedSystemPolicies");

                    b.Navigation("DeviceInstallations");

                    b.Navigation("EmergencyUnlocks");

                    b.Navigation("IncidentActions");

                    b.Navigation("LockerAccessEvents");

                    b.Navigation("LockerEvents");

                    b.Navigation("MaintenanceActivities");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Notifications");

                    b.Navigation("OperatorAssignments");

                    b.Navigation("OtpChallenges");

                    b.Navigation("ParcelStatusChanges");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RemovedParcels");

                    b.Navigation("ReportedIncidents");

                    b.Navigation("ResidentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
